repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: no-commit-to-branch
    args: ['--branch', 'main']
  - id: mixed-line-ending
  - id: check-merge-conflict
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
