FROM eclipse-temurin:17-jre-focal

# Run as non-root user
RUN groupadd -g 322 lavalink && \
    useradd -r -u 322 -g lavalink lavalink
USER lavalink

# Download Lavalink
WORKDIR /opt/Lavalink
ADD --chown=322:322 \
    https://github.com/Cog-Creators/Lavalink-Jars/releases/latest/download/Lavalink.jar \
    Lavalink.jar

ENTRYPOINT ["java", "-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2", "-Xmx512M", "-jar", "Lavalink.jar"]
