FROM eclipse-temurin:16

# Download latest Lavalink jar
ADD https://github.com/Cog-Creators/Lavalink-Jars/releases/latest/download/Lavalink.jar /opt/app/Lavalink.jar

# Copy configuration file
COPY lavalink.yml /opt/app/application.yml

# Run jar
WORKDIR /opt/app
CMD ["bash", "-c", "java -jar Lavalink.jar"]
