FROM eclipse-temurin:16

# Don't run as root
RUN groupadd -g 322 lavalink && \
    useradd -r -u 322 -g lavalink lavalink
USER lavalink

# Download latest Lavalink jar
WORKDIR /opt/app
ADD --chown=322:322 \
    https://github.com/Cog-Creators/Lavalink-Jars/releases/latest/download/Lavalink.jar \
    Lavalink.jar

# Run jar
ENTRYPOINT ["java", "-jar", "-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2", "-Xmx4G", "Lavalink.jar"]
