version: '1'

services:
  lavalink:
    image: jareddantis/cogcreators-lavalink:latest
    volumes:
      - ./lavalink.yml:/opt/app/application.yml
  bot:
    image: blancobot
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - lavalink
    env_file:
      - .env
