version: '1'
services:
  lavalink:
    image: jareddantis/cogcreators-lavalink:latest
    ports:
      - '2333:2333'
    volumes:
      - ./lavalink.yml:/opt/app/application.yml
  bot:
    image: jareddantis/discord-bot-base:latest
    depends_on:
      - lavalink
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DISCORD_BOT_TOKEN: '${DISCORD_BOT_TOKEN}'
      DISCORD_BOT_PREFIX: '${DISCORD_BOT_PREFIX}'
      PYTHONUNBUFFERED: '1'
    command:
      - bash
      - -c
      - "pip install -r requirements.txt && python main.py"
