version: '1'
services:
  lavalink:
    image: jareddantis/cogcreators-lavalink:v2
    ports:
      - '2333:2333'
    working_dir: /opt/app
    command:
      - bash
      - -c
      - "java -jar Lavalink.jar"
  bot:
    image: jareddantis/discord-bot-base:v2
    depends_on:
      - lavalink
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DISCORD_BOT_TOKEN: '${DISCORD_BOT_TOKEN}'
      DISCORD_BOT_PREFIX: '${DISCORD_BOT_PREFIX}'
      PYTHONUNBUFFERED: '1'
    command:
      - bash
      - -c
      - "python main.py"
