version: '1'

services:
  lavalink:
    image: jareddantis/cogcreators-lavalink:latest
    volumes:
      - ./lavalink.yml:/opt/app/application.yml
  bot:
    image: blancobot
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - lavalink
    volumes:
      - .:/app
    env_file:
      - .env
    command:
      - bash
      - -c
      - "python3 main.py"
