from .dashboard import dashboard
from .deleteaccount import delete_account
from .discordoauth import discordoauth
from .homepage import homepage
from .lastfmtoken import lastfm_token
from .linklastfm import link_lastfm
from .linkspotify import link_spotify
from .login import login
from .logout import logout
from .spotifyoauth import spotifyoauth
from .unlink import unlink
