name: Test build Docker Image for PRs

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      IMAGE_FLAVOR: |
        latest=false
      ADDITIONAL_TAGS: |
        type=raw,staging
