name: Test build Docker Image for PRs

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      IMAGES: |
        ghcr.io/${{ github.repository }}
      IMAGE_FLAVOR: |
        latest=false
