name: Build new latest image

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPOSITORY: 'jareddantis/blanco-bot'
      IMAGES: |
        ghcr.io/${{ github.repository }}
        'jareddantis/blanco-bot'
      IMAGE_FLAVOR: |
        latest=true
      IMAGE_TAGS: |
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=sha,prefix=
