name: Docker Image CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build and push image to GHCR and Docker Hub
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_PACKAGE_TOKEN }}
    -
      name: Delete all prior versions on GHCR
      uses: actions/delete-package-versions@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        package-name: ${{ github.event.repository.name }}
        min-versions-to-keep: 0
    -
      name: Get image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ github.repository }}
          ghcr.io/${{ github.repository }}
    -
      name: Checkout repository
      uses: actions/checkout@v3
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
