name: Docker Image CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  DOCKERHUB_REPOSITORY: 'jareddantis/blanco-bot'

jobs:
  build:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Get image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.DOCKERHUB_REPOSITORY }}
    -
      name: Checkout repository
      uses: actions/checkout@v3
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.DOCKERHUB_REPOSITORY }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Update Docker Hub readme
      uses: ms-jpq/sync-dockerhub-readme@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ env.DOCKERHUB_REPOSITORY }}
        readme: "./README.md"
