name: Lint and build image for PR

on:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use 3.12
          poetry install
      - name: Run linter
        run: |
          poetry run ruff check --no-fix --no-cache $(git ls-files '*.py')
      - name: Run format checker
        run: |
          poetry run ruff format --check --no-cache $(git ls-files '*.py')
  build:
    uses: ./.github/workflows/build.yml

    with:
      IMAGE_FLAVOR: |
        latest=false
