name: Build staging image

on:
  push:
    branches:
      - 'next'
    paths-ignore:
      - '**.md'

jobs:
  build:
    uses: ./.github/workflows/build.yml

    with:
      IMAGE_FLAVOR: |
        latest=false
