name: Build staging image

on:
  push:
    branches:
      - 'next'

jobs:
  build:
    uses: ./.github/workflows/build.yml

    with:
      IMAGE_FLAVOR: |
        latest=false
      ADDITIONAL_TAGS: |
        type=raw,staging
